name: Slack Notify on Star
on: watch
jobs:
  star-notify:
    name: Slack Notify on Star
    runs-on: ubuntu-latest
    steps:
    - name: Get current star count
      run: |
        echo ::set-env name=STARS::$(curl --silent 'https://api.github.com/repos/meshery/meshery-adapter-library' -H 'Accept: application/vnd.github.preview' | jq '.watchers_count')
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CSK7N9TGX\",\"text\":\"${{ github.actor }} just starred Meshery Adapter Library! (https://github.com/meshery/meshery-adapter-library/stargazers) Total ⭐️: ${{env.STARS}}\"}'
